version: '2'

services:
  elasticsearch:
    image: elasticsearch:latest
    #command: elasticsearch -Des.network.host=0.0.0.0
    command: elasticsearch -Des.network.host=0.0.0.0
    restart: unless-stopped
    volumes:
      - /data/elk-data:/usr/share/elasticsearch/data:Z

  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    restart: unless-stopped
    volumes:
      - ./logstash/config:/etc/logstash/conf.d:ro,Z
    ports:
      - "5000:5000"
      - "42185:42185/udp"
      - "42185:42185/tcp"
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    restart: unless-stopped
    volumes:
      - ./kibana/config/:/opt/kibana/config/:ro,Z
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/config:/etc/nginx/conf.d:ro,Z
      - ./nginx/htpasswd.users:/etc/nginx/htpasswd.users:ro,Z
    ports:
      - "5601:5601"
    depends_on:
      - kibana
